exemplo:
	cc exemplo.c -o seila.out && ./seila.out && rm seila.out

exercicio1:
	cc execicio1.c -o seila.out && ./seila.out && rm seila.out

exercicio2:
	cc execicio2.c -o seila.out && ./seila.out && rm seila.out